FROM ubuntu:24.04

RUN apt-get update && echo 1
RUN apt-get install -y --no-install-recommends \
	  git \
	  curl 

RUN apt-get install -y --no-install-recommends \    
    ripgrep \
    gcc \ 
    make \
    libc-dev
    
RUN apt-get install -y --no-install-recommends \ 
    ca-certificates

    # npm \ 
    # python3.11-minimal \
    # python3.11-venv \
    # python3-neovim \
    # pip

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && \
   chmod u+x nvim.appimage && \
   ./nvim.appimage --appimage-extract && \
   ln -s /squashfs-root/AppRun /usr/bin/nvim

RUN git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
# RUN git clone https://github.com/dreamsofcode-io/neovim-python.git ~/.config/nvim/lua/custom

# M.ui = { theme = 'one_light' }

#RUN apt-get install -y --no-install-recommends \
#    libc-dev # =2.38+

RUN apt-get install -y --no-install-recommends \ 
   clang

RUN apt-get install -y --no-install-recommends \
  unzip

RUN apt-get install -y --no-install-recommends python3.11 python3.11-venv

COPY cpp /root/.config/nvim/lua/custom
